config:
  root: examples/saxswaxs
  outputdir: output
  log_level: debug

pipeline:

  # Download example data
  - common.URLReader:
      url: https://gitlab01.classe.cornell.edu/api/v4/projects/308/repository/files/saxswaxs%2fdata.tar/raw?ref=main
      headers:
        PRIVATE-TOKEN: # your token here
  - common.ExtractArchiveWriter:
      filename: examples/saxswaxs

  # Collect / organize raw datasets
  - common.MapReader:
      map_config:
        title: test_1d
        station: id3b
        experiment_type: SAXSWAXS
        sample:
          name: sample_14_align
        spec_scans:
        - spec_file: test_1d
          scan_numbers:
          - 1
        independent_dimensions:
        - label: samx
          units: mm
          data_type: spec_motor
          name: samx
        presample_intensity:
          data_type: scan_column
          name: ic3
        dwell_time_actual:
          data_type: scan_column
          name: sec_2
        postsample_intensity:
          data_type: scan_column
          name: diode
      detector_names: 
        - PIL5
        - PIL9
        - PIL11
  - common.NexusWriter:
      filename: map.nxs
      force_overwrite: true
  # # (Or: read in pre-collected / organized raw data)
  # - common.NexusReader:
  #     filename: map.nxs
  #     nxpath: test_1d

  # Prepare for integration
  - saxswaxs.PreIntegrationReader:
      detectors:
        - nxfield_path: data/PIL9
          poni_file: PIL9.poni
          mask_file: PIL9.tif
        - nxfield_path: data/PIL11
          poni_file: PIL11.poni
          mask_file: PIL11.tif

  # Perform integration
  - saxswaxs.IntegrationProcessor:
      config:
        title: waxs_azimuthal
        integration_type: azimuthal
        radial_units: q_A^-1
        radial_min: 0.0
        radial_max: 3.33209
        radial_npt: 200
        azimuthal_units: chi_deg
        azimuthal_min: -180 #100
        azimuthal_max: 180 #360
        azimuthal_npt: 180
        error_model: poisson
        right_handed: true

  # Save results
  - common.NexusWriter:
      filename: map.nxs
      nxpath: /
      force_overwrite: true